### ISSUE TITLE
Another compilation issue

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#141] opened 2023-09-02 13:36 UTC
use MakeOptTFT.bat

Error reporting
Scripts\TFT\common.ai:18046: Undeclared variable hero_unit

```

original
if GetUnitAbilityLevel(hero_unit[hn], 'AOwk') > 0 or GetUnitAbilityLevel(hero_unit[hn], 'ANwk') > 0 then

compilation
if GetUnitAbilityLevel(v448[hn],'AOwk') > 0 or GetUnitAbilityLevel(hero_unit[hn], 'ANwk')>0 then

```

The second hero_unit[hn] recognized as undefined , But this is a global variable

**Comment by jzy-chitong56** [comment] 2023-09-02 13:55
Scripts\ROC\common.ai:22889: Missing endif
Scripts\ROC\common.ai:22890: Missing endfunction


it looks as if     **if false then**  Unable to recognize

original
```
call Sleep(5 * sleep_multiplier)
  if false then
  #INCLUDETABLE <$VER$\HealingItems.txt> #EFR #COND "%1" eq "RITUAL_DAGGER"
  elseif GetItemTypeId(heal_item) == old_id[%1] then  //prevent killing high health units
    set target = FirstOfGroup(urgent)
    if target != null then
      call UnitUseItemTarget(u, heal_item, target)
      call GroupRemoveUnit(urgent, target)
    endif
  else
  #ENDINCLUDE
    loop
      exitwhen not UnitHasItem(u, heal_item)
      set target = FirstOfGroup(urgent)
      if target != null then
        call UnitUseItemTarget(u, heal_item, target)
        call GroupRemoveUnit(urgent, target)
      else
        set target = FirstOfGroup(medium)
        if target != null then
          call UnitUseItemTarget(u, heal_item, target)
          call GroupRemoveUnit(medium, target)
        endif
      endif
      exitwhen target == null
      call Sleep(2 * sleep_multiplier)
    endloop
  endif
```

compilation

```
call Sleep(5*v100)
loop
  exitwhen not UnitHasItem(u,v915)
  set v24e=FirstOfGroup(v916)
  if v24e!=null then
    call UnitUseItemTarget(u,v915,v24e)
    call GroupRemoveUnit(v916,v24e)
  else
    set v24e=FirstOfGroup(v917)
    if v24e!=null then
      call UnitUseItemTarget(u,v915,v24e)
      call GroupRemoveUnit(v917,v24e)
    endif
    exitwhen v24e==null
    call Sleep(2*v100)
endloop
endif
```

**Comment by SMUnlimited** [comment] 2023-09-03 15:06
I cannot reproduce in master including your PR changes merged.

**Comment by jzy-chitong56** [comment] 2023-09-04 06:12
It's okay. If I synchronize all the code, maybe you can encounter it

**Comment by SMUnlimited** [comment] 2023-09-19 22:19
I hate regex! Fixed in https://github.com/SMUnlimited/AMAI/commit/f22c2395254b7e004b66ee7bfacae78fb18d6992#diff-6060a094116a49cd2568ea0bbb9cefcf3306e20676b1eaf7778d12c71f4077be

**Closed** 2023-09-20 07:07 UTC
Labels: invalid
