### ISSUE TITLE
laggy and collapse report

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#115] opened 2022-12-11 07:52 UTC
**Test settings
1 human player is Observer
23 player is  AI , all INSANE 
7v8v8 or 11v12**

When  AI food  > 50   , the game start laggy 
When  AI food  > 90 , the game is PPT or collapse

@SMUnlimited 

but if use my pull requests , 1v1v1v1v1v....v1 or 3v3v3v2v2v2v2v1v1v1v1v1 ， the game no laggy 

The conclusion maybe is ，when  AI ally > 3 , the game will laggy 

one key is function TQLoop
        call Sleep(RMin(tq_time[1] - TimerGetElapsed(tq_timer) + 0.05 ,1))

tq_time[1] - TimerGetElapsed(tq_timer) + 0.05 some time < 0

-----------------------------------------------------------
The problem is
**The loop contains too many IsUnitInGroup**
IsUnitInGroup maybe is loop too
so have too much loop , then laggy and collapse

-----------------------------------------------------------
and if we notes the code

```
//call TQAddJob(4, ARMY_TRACK, 0)

//call TQAddJob(GetRandomReal(50, 60), ARMY_TRACK, 0)
```
or

```
  //call TrackExistingArmies()
  //call SeedNewArmies()
```

the game no laggy , extraordinary silky

I suspect the problem is
```
  call TrackExistingArmies()
  call SeedNewArmies()
```

but if TrackArmy normal run , here should be no leakage , I really can't find a problem

and  TOWN_TRACK ， they have similar structures and need to be checked

-------------------------------------------------------------------------

That no help
```
function SeedNewArmyAtLoc takes location l, integer p returns nothing
  if army_loc[army_num] != null then
    set army_num = army_num + 1
  endif
  set army_owner[army_num] = p
  set army_loc[army_num] = l
  set army_dir[army_num] = null 
  set army_future[army_num] = null 
  set army_group[army_num] = CreateGroup()
  if TrackArmy(army_num) then
     set army_num = army_num + 1
  endif
endfunction
```

or

```
function SeedNewArmyAtLoc takes location l, integer p returns nothing
  set army_owner[army_num] = p
  set army_loc[army_num] = l
  set army_dir[army_num] = Location(0,0)
  set army_future[army_num] = Location(0,0)
  set army_group[army_num] = CreateGroup()
 // if TrackArmy(army_num) then
     set army_num = army_num + 1
  //endif
endfunction
```

and this too

```
function CopyArmy takes integer from, integer to returns nothing
  set army_owner[to] = army_owner[from]
  set army_loc[to] =  Location(GetLocationX(army_loc[from]),GetLocationY(army_loc[from]))
    call RemoveLocation(army_loc[from])
  set army_dir[to] = Location(GetLocationX(army_dir[from]),GetLocationY(army_dir[from]))   
    call RemoveLocation(army_dir[from])
  set army_future[to] =  Location(GetLocationX(army_future[from]),GetLocationY(army_future[from]))  
        call RemoveLocation(army_future[from])
  set army_strength[to] = army_strength[from]
  set army_group[to] = call BlzGroupAddGroupFast(army_group[from],army_group[to])
  call DestroyGroup(army_group[from])
  set army_count[to] = army_count[from]
endfunction
```

or

```
function SeedNewArmiesForPlayer takes integer p returns nothing
  local group g = CreateGroup()
  local unit u = null
  call GroupEnumUnitsOfPlayer(g, Player(p), null)
  set g = SelectByUnitStandard(g, true)   // Hopefully fix issues of heroes doing other things not making false armies
  loop
    set u = FirstOfGroup(g)
    exitwhen u == null
    if UnitAlive(u) and not IsUnitInGroup(u, in_army_group) and (IsUnitType(u, UNIT_TYPE_HERO) or major_hero == u ) then 


 //or (GetRandomInt(0, 30) == 1 and not (IsUnitType(u, UNIT_TYPE_STRUCTURE) or IsUnitType(u, UNIT_TYPE_PEON)))) then
      call SeedNewArmyAtLoc(GetUnitLoc(u), p)
    endif
    call GroupRemoveUnit(g, u)
  endloop
  call DestroyGroup(g)
  set g = null
endfunction
```

-------------------------------------------------------------------------------

**FIX**

trying

**Comment by SMUnlimited** [comment] 2023-12-13 16:48
Duplicate of #187

**Closed by SMUnlimited** 2023-12-13 16:48 UTC
Labels: duplicate
