### ISSUE TITLE
AI Problems in Map (10)dustwallowkeys

### ISSUE THREAD

**Issue by edsson-malorne** [SMUnlimited/AMAI#323] opened 2024-06-06 03:00 UTC
Map issues (10)dustwallowkeys, AI does not recognize the default starting gold mine and leaves another nearby gold mine to collect at certain starting points.
![Captura de pantalla 2024-06-05 220454](https://github.com/SMUnlimited/AMAI/assets/145234401/1876ddb1-7f58-4840-be27-921af98feb8c)

**Comment by jzy-chitong56** [comment] 2024-06-06 07:38
use 3.3.5?

**Comment by jzy-chitong56** [comment] 2024-06-06 07:40
use 3.3.5?

**Comment by jzy-chitong56** [comment] 2024-06-06 07:41
use 3.3.5?

**Comment by edsson-malorne** [comment] 2024-06-06 14:59
> usar 3.3.5?

Yes, I'm always looking forward to your updates, I've only found this problem on that map.
![Captura de pantalla 2024-06-06 095627](https://github.com/SMUnlimited/AMAI/assets/145234401/ed7231dd-b838-44c2-a584-6603649830a6)

**Comment by edsson-malorne** [comment] 2024-06-06 15:09
I just remembered another map that has nearby mines, ''(8)friends'', and as I suspected the same bug occurred.
![Captura de pantalla 2024-06-06 100513](https://github.com/SMUnlimited/AMAI/assets/145234401/6f26212f-a550-4703-9ba8-7370e805d3f2)
![Captura de pantalla 2024-06-06 100500](https://github.com/SMUnlimited/AMAI/assets/145234401/9004a853-3ef0-47b5-91f9-e653332ede47)

**Comment by SMUnlimited** [comment] 2024-06-06 16:03
Confirmed but its hardcoded blizzard functions causing this.
Some AI's GetMinesOwned() returns 2 instead of 1, leaving the AI that supposed to own the mine having to own the mine behind the trees.

**Comment by jzy-chitong56** [comment] 2024-06-06 17:32
In theory, there will be some intervention after the multi mine fix and detection code work, trying to increase the initialization search distance

**Comment by edsson-malorne** [comment] 2024-06-07 19:57
> @edsson-malorneelf y UD, ¿es normal?

Elves are also affected, they send Wisps and don't build anything. Undead seem to work fine, I guess it's because they can only build on plagued terrain.
![Captura de pantalla 2024-06-07 144856](https://github.com/SMUnlimited/AMAI/assets/145234401/a454e020-6473-49c3-b98c-250c76261c02)
![Captura de pantalla 2024-06-07 144946](https://github.com/SMUnlimited/AMAI/assets/145234401/28ffef2e-ad3a-4aea-99a1-ed8b5785056b)

**Comment by paulo101977** [comment] 2024-06-07 20:29
> Confirmed but its hardcoded blizzard functions causing this. Some AI's GetMinesOwned() returns 2 instead of 1, leaving the AI that supposed to own the mine having to own the mine behind the trees.

This bug is very old, if you doubt it, it is over 15 years old... The two maps mentioned always have problems related to the positioning of the AI ​​on the map.

**Comment by jzy-chitong56** [comment] 2024-06-08 17:48
I fixed it here, and the collection is basically normal now
But there are issues with the construction of UD and ELF, and the altar will be placed at the starting point of other players. I think the easiest way is to repair it in the collection task, but the collection task itself is not for construction repair. You may not like this kind of mixture very much

There is another issue - InitCheckHarvest cannot accurately determine the pattern

The number of GLOD and RACE GLOD varies in different games for the same location, and the same applies to GetMinesOwned()

I have a theory, but I'm not sure if language can explain it clearly, but I really don't want to draw (and maybe I can't draw it clearly)

Assumption: There are two starting points, only two gold mines
Process: BJ creates initial unit>>BJ  Enable AI>>>AI script starts working>>>AI script runs to InitCheckHarvest function

When Player 1 runs to InitCheckHarvest, assuming that Player N (N>1) has not yet created the initial unit, the gold mine will be marked as unowned (which may cause `GetMinesOwned()>1`)
Of course, if player N is UD or ELF, then when player 1 detects, at most they only have their own race gold mine, so there is 1 gold mine, and race gold mine has 1（_Player N (N>1) has not yet created the initial unit_）， because race gold mines are built on top of gold mines, and it seems that there will be no repeated calculations when looking at the logs
But when it's player N's turn to run to InitCheckHarvest, he will find that the mine is owned by someone. This is his race's gold mine, which can have up to 2 gold mines and 0 gold mines

**Comment by jzy-chitong56** [comment] 2024-06-11 16:53
Preliminary repair completed
Including the issue of going to nearby player locations to build buildings -- If the two are in a hostile relationship, it would be a disaster

But my branch will suddenly crash after running for 1 hour for an unknown reason

**Comment by SMUnlimited** [comment] 2024-11-27 23:38
I've overridden the mining logic in first stab in latest commit rather than introduce workaround jobs for it.

**Comment by jzy-chitong56** [comment] 2024-11-28 01:17
I think there are at least two issues. One is that the undead are not using public code, which cannot be fixed here. The second is that you seem to be affecting the expansion of collection,

As a basic function, will using unit groups have a significant impact on efficiency、job At least it doesn't need to run every time

Finally, elf did not use this code, and their problem of placing buildings in other player bases has not been fixed

**Comment by jzy-chitong56** [comment] 2024-11-28 16:09
Using the current `HARVEST_CHECK` logic can handle it well, there is no need to rewrite this https://github.com/SMUnlimited/AMAI/commit/5dfba6c67d20940aa0ae7dcb5cdf98ded404e913

Just need to pay attention periodically, there's no need to force all units to be searched every time, it really affects efficiency
And you disabled the Harvest hard coding of `InitCheckHarvest`, which resulted in the failure of UD's repair function

**Comment by SMUnlimited** [comment] 2024-11-28 20:21
I've fixed the above. Yes i do need to update logic so harvest_check and the single mine logic do not conflict or part merged together, but need to merge rest of your changes before i can start working on that. 

It is in the right place as i've overridden the entire harvestgold logic as that is what was making units walk away to far away gold mines which can happen for cases where there is only a single mine owned (because another human/orc player technically owns the mines) which harvestcheck doesn't handle right now.

**Comment by jzy-chitong56** [comment] 2024-11-29 01:28
You need to test this map, which is also a very special case
I don't know what the English name is, but you should be able to tell which one it is at a glance

https://www.bilibili.com/video/BV1C7411g7q8/?spm_id_from=333.788.videocard.3

Finally, do you plan to handle `FIXBUILD`?

**Closed** 2024-11-30 16:39 UTC
Labels: bug, hardcoded

**Comment by Slayer95** [comment] 2024-12-01 02:49
> You need to test this map, which is also a very special case I don't know what the English name is, but you should be able to tell which one it is at a glance
> 
> https://www.bilibili.com/video/BV1C7411g7q8/?spm_id_from=333.788.videocard.3
> 
> Finally, do you plan to handle `FIXBUILD`?

That map is called (4)Synergy. Very similar to (8)Friends.
