### ISSUE TITLE
Performance degradation caused by Army_Track and TOWN_TRACK

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#187] opened 2023-11-13 08:59 UTC
when more than 10 AI allies , fps will go 10 
when 23 AI allies , fps will go 0 

https://github.com/SMUnlimited/AMAI/issues/159

----------------------------------------------------------------------------------------------------------
but , if not run this code , fps have 40
 
```
  call GroupClear(in_army_group)
  call TrackExistingArmies()
  call SeedNewArmies()
```

----------------------------------------------------------------------------------------------------------
Guess it's because **IsUnitInGroup**

But it's completely impossible to handle 
don't know how to rewrite these two job , because **IsUnitInGroup** is key , cannot DELETE
I tried assigning an in_army_group to each player ， in_army_group[player_num] , but fps not improve
_Perhaps can try adjust adding group logic the hero unit to reduce the use of **IsUnitInGroup**_ 

_Guess 
One reason is that when 1v23,  AI's army will be concentrated at the birthplace of the only enemy
But the newly trained units are all in their respective birthplaces of AI, and before they arrive on the battlefield, they are very far away from the army and will be set as independent armies
so army_num will increase , check IsUnitInGroup will increase too
At the same time, the enemy used **whosyourdaddy** and did not build any army, resulting in the AI's army not being downsized , in_army_group unit number not being downsized ..._

----------------------------------------------------------------------------------------------------------
According to job logic , At least one army per player , maybe more 
Testing found that when the army_num total number of troops reaches 30, fps will go 0 ,  Even at this point , the army_num of troops is zero

----------------------------------------------------------------------------------------------------------
The same problem still occurs on TOWN_TRACK

**Comment by jzy-chitong56** [comment] 2023-11-14 01:57
If each player is assigned an in_ Army_Group[i]

And increase the frequency interval based on the **number of allies - number of enemies+1**

Randomly acquire non hero units by increasing the total number of players **(0, 30 + number of allies + number of enemies+1)**

The FPS of 1V23 can be reduced to a maximum of 2 and can be restored to between 8 and 10+, and the game can still be operated


------------------------------------------------------------------------------------------------
But I don't know if increasing the frequency will affect the timeliness of AI's detection of urban threats


------------------------------------------------------------------------------------------------
The same change to TOWN_TRACK

**Comment by jzy-chitong56** [comment] 2023-11-25 02:13
Some variables in my branch were mistakenly cleared, causing this issue, but your branch did not synchronize this code. Currently, it can be confirmed that there are other codes that can cause FPS to drop to 0, but at least after fixing the clearing, the game can run normally until the end

**Comment by SMUnlimited** [comment] 2023-12-12 18:18
Can reproduce and investigating, it is specifically the army track. Fixed a seperate bug and that also makes 12 players hit the lag as well.

But seems the array sizes are growing way too fast than it should be over 100-300. Also debugging is showing some duplication "which could mean the job is firing twice in quick succession" as well.

**Comment by SMUnlimited** [comment] 2023-12-13 08:43
Fixed on my side 12 v 11 worked smoothly now. Made some small optimizations but mostly seems to have been too much happening in a short amount of time in effect turning into an infinite loop with not enough rest time.

**Comment by jzy-chitong56** [comment] 2023-12-13 08:50
[Uploading (24)Emersion v3.0 Standard Melee.w3x.zip…]()
my test will crash , use this map . Even if all JOB are disabled

**Comment by SMUnlimited** [comment] 2023-12-13 10:23
When did it crash for you, immediately or over time?
Only lag is at game start when all the invisible pathing units are spawning in but post that now smooth.

**Comment by jzy-chitong56** [comment] 2023-12-13 10:31
Random
Sometimes it starts soon, sometimes it's very late
should not pathing units

**Comment by SMUnlimited** [comment] 2023-12-13 16:15
After more testing I still hit some lag spikes during some very large battles, but game did complete. 

If you still get lag with JOBs disabled it is either something else entirely or the limits of the game engine with that many units and effects on screen. 

I had debug mode on too so that will make it a bit slower than it would be in reality as well.

**Comment by jzy-chitong56** [comment] 2023-12-13 16:30
I'm glad my bug code didn't sync with you

**Comment by SMUnlimited** [comment] 2023-12-13 16:58
> town_threat_army[num] most_threatened_town most_threatened_enemy_town
> 
> this not copy on **CopyArmy** and **CopyTown** , Is this intentional?

Hmm yes and no. No because they get recalculated but yes because after CopyTown the most_threatened_town would no longer be pointing at the right town anymore. But thats not recalculated until the ARMY_TRACK runs so would be out of sync for a time.

**Comment by SMUnlimited** [comment] 2023-12-13 17:38
Out of interest the `SelectBy, SelectUnitType` in your code are probably what was killing performance on your end as each one of those iterates the groups multiple times to apply the filter and doing all of that without a sleep operation in addition to the current logic probrably locks the thread.

While my code just iterates the group once so it has less impact.

**Comment by jzy-chitong56** [comment] 2023-12-14 04:14
In fact, the **SelectBy, SelectUnitType** operation of adding unit groups has little impact on performance, mainly due to errors in certain areas
After I fixed it, FPS also has 40, but I haven't had time for a complete test yet

**Comment by jzy-chitong56** [comment] 2023-12-14 14:37
SeedNewArmiesForPlayer should avoid UNIT_TYPE_SUMMONED
TrackArmy should check FirstOfGroup(army_group[num]) alive
UpdateSpecificTownThreat should avoid all own armies
```
    if Player(army_owner[i]) == ai_player or Player(army_owner[i]) == Player(town_owner[num]) then
      set i = i + 1
    endif
```

**Comment by SMUnlimited** [comment] 2023-12-14 14:58
Well with 3.3.0 released we do have the luxury to continue experimenting. 

I'm pretty confident its the long execution time with 0 breaks and having more players is hitting that more often or more threads running long loops.  12 player lag is now completely gone.

**Comment by SMUnlimited** [comment] 2023-12-14 15:32
SeedNewArmiesForPlayer should avoid UNIT_TYPE_SUMMONED - Not really, army should include all units to get most idea of risk. Otherwise a purely summoned skeleton army AMAI would ignore which would be bad. 
TrackArmy should check FirstOfGroup(army_group[num]) alive - Not required its only used for the location, if its dead it will still be close to rest of army
UpdateSpecificTownThreat - It should and that looks like a bug to ignore the players armies in the first place.

**Comment by SMUnlimited** [comment] 2023-12-15 14:08
Merged new change that seems to deal with the final lag spikes that could kill the game during massive battles. Looking much better now but need others to test it out.

**Comment by jzy-chitong56** [comment] 2023-12-15 14:16
I opened the job and the thread still crashes, still checking, but I will synchronize your modifications and release a beta version for willing players to test

**Comment by jzy-chitong56** [comment] 2023-12-15 15:31
I synchronized the modifications and found that the added sleep is mostly in a loop. The more units there are, the greater the delay, which may cause AI to become foolish

- In fact, there is no need to sleep when the number of players does not exceed 10
- Additionally, I still recommend moving non combat job into the PATH thread to make up for some lost waiting time

**Closed** 2024-03-04 06:02 UTC
Labels: bug
