### ISSUE TITLE
Commander and translation issues

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#74] opened 2022-09-04 12:42 UTC
- BuildStartDialog on Page Break

-  Dialog only show title at first

-  Dialog cannot change language 

mabey Previous button It should be on the top

my eai should fix Dialog only show title at first and  Dialog cannot change language 
but` infinite paging` , i can not help , so sorry(try fixing)
it is here
https://github.com/jzy-chitong56/AMAI/blob/master/Blizzard.eai

![QQ图片20220904201409](https://user-images.githubusercontent.com/48715223/188313265-8ad7eb65-0039-47d2-b27f-043cd8a3fcdd.png)

**Comment by SMUnlimited** [comment] 2022-09-04 15:24
These should be fixed already by my recent commits https://github.com/SMUnlimited/AMAI/commit/5a33db9aa327984762a665de895ff718bbc738bf and https://github.com/SMUnlimited/AMAI/commit/001703f1f83b99cc40e918815041b3d1823774c8

**Comment by jzy-chitong56** [comment] 2022-09-04 16:48
> * Dialog only show title at first
> * Dialog cannot change language

no fix ,here on title 
![=image](https://user-images.githubusercontent.com/48715223/188324045-3b8c90d6-7f16-43a4-9bed-1759abb24edd.png)

and here  , i set chinese , then change english , but Dialog no change ( i set on AI Setting) , maybe AI Setting no need language button
![image](https://user-images.githubusercontent.com/48715223/188324057-6ad8039b-01b7-4e78-9edb-3f099cac654a.png)

and clanguage_button ,  no adapted language....

**Comment by SMUnlimited** [comment] 2022-09-04 21:59
Aha I now reproduced the missing title. Seems to go wrong with the all ally button. 

AI language does not affect commands as the commander is not directly linked to AI's. You can set every AI to be a different language in the commander but responses to the commander will always be in one language because the commander is only translated to 1 language. The command language option makes that clearer its different instead of hiding away and is more customizeable.

The missing translation for command language suggests to me a bug in the translation logic as should at least default to english not blank text.

**Comment by jzy-chitong56** [comment] 2022-09-04 23:56
> Aha I now reproduced the missing title. Seems to go wrong with the all ally button but will investigate.
> 
> AI language does not affect commands as the commander is not directly linked to AI's. You can set every AI to be a different language in the commander but responses to the commander will always be in one language because the commander is only translated to 1 language. The command language option makes that clearer its different instead of hiding away and is more customizeable.
> 
> The missing translation for command language suggests to me a bug in the translation logic as should at least default to english not blank text.

If you want to set the command language button  Put it outside，It may be necessary to set the top,Because if I have more than 10 allies,The button will go to the second page

**Comment by SMUnlimited** [comment] 2022-09-05 16:25
I missed some of your changes @jzy-chitong56 so those seem to help. 

But I have got to rebuild the static dialogs on language change to get the translation selection to hold.

**Comment by jzy-chitong56** [comment] 2022-09-05 17:47
> I missed some of your changes @jzy-chitong56 so those seem to help.
> 
> But I have got to rebuild the static dialogs on language change to get the translation selection to hold.

I want to help ， but I cannot 
i fix...not very successful
https://github.com/jzy-chitong56/AMAI/blob/2.6.x/TEST

know problems   

- only dlghdr_tribute_type show title at first , but other normal 
- The language of the inner button(CommandsTrans.txt) has not been changed
（and i set dlgbutton_previous_page to Top, good day ,I must go to bed ，If I do something wrong， sorry）
like this
![image](https://user-images.githubusercontent.com/48715223/188495599-a0837665-fe52-4ad7-8f8d-0a681b992b11.png)
![image](https://user-images.githubusercontent.com/48715223/188495637-dc552533-ebdf-47bd-8293-a7b7fd5b3cab.png)

**Comment by jzy-chitong56** [comment] 2022-09-06 00:17
@SMUnlimited 
I try one time
the Dialogs have change language , but original Dialogs not cleared , new language  button appears at the bottom
maybe call DialogDestroy all Dialogs , Rebuild Dialogs and all button ， the language can change

**Comment by SMUnlimited** [comment] 2022-09-06 16:30
Solved

**Closed** 2022-09-06 16:29 UTC

**Comment by jzy-chitong56** [comment] 2022-09-06 16:55
> Solved
if you need , i have W3C map 
https://github.com/jzy-chitong56/amai-map (Install master - 2022-09-07 0:49 [UTC+0800] , It's the version of the  Dialogs  language you just “Solved”)

they used lua , so map cannot run amai ,  so i change to jass ， but price is W3C command invalid
I do duplicate removal map(Keep the latest version)
At least, players have new map
